apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphiti.fullname" . }}-vars
  labels:
    {{- include "graphiti.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.vars }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 