name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.4.0
      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
          helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do
            repo_name=$(echo $cmd | awk '{print $4}')
            if ! helm repo list | grep -q $repo_name; then
              $cmd
            else
              echo "Repository $repo_name already exists"
            fi
          done
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
            skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_KEY: ${{ secrets.CR_KEY }}  #Key name used while creating key
          CR_SIGN: true # set to true to sign images